server:
  port: 8091

spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

dgs:
  graphql:
    graphiql:
      enabled: false
    header:
      validation:
        enabled: false